import $ from "jquery";
window.$ = window.jQuery = $;
window.jQuery.migrateMute = true;
require("./libs/jquery.elevatezoom");
require("jquery-hoverintent");
require("lazysizes/plugins/object-fit/ls.object-fit");
require("lazysizes/plugins/parent-fit/ls.parent-fit");
require("lazysizes/plugins/rias/ls.rias");
require("lazysizes/plugins/bgset/ls.bgset");
require("lazysizes");
require("lazysizes/plugins/respimg/ls.respimg");
require("./libs/alpine");
require("./libs/typeahead.bundle");
// window.Instafeed = require("instafeed.js");
